### ISSUE TITLE
Upper Extremity Kinematic Model stops updating visualizer after awhile

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#552] opened 2018-02-26 21:37 UTC
### Steps to reproduce
Import into 3.3 and load into 4.0 as in #551.

Keep moving the Coordinate sliders around for a bit (usually after ~ 1 min)

### Expected result
The visualizer keeps updating.

### Actual result
The visualizer stops updating to Coordinate changes. Closing the model and reopening it fixes the problem for a bit, until it stops updating again.

### Environment and GUI version
Windows 10, 022518-win64

**Comment by aymanhab** [comment] 2018-03-01 01:35
Basically if the communication pipe is broken due to an exception or flooding then the visualizer will stop responding. We need to find what changes were made, and what's special about this model.

**Comment by jenhicks** [comment] 2018-04-10 17:40
Closing unless there are some more specific steps to reproduce or it recurs with other models

**Closed by jenhicks** 2018-04-10 17:40 UTC
Labels: Visualization
