### ISSUE TITLE
Syncing motion does not render associated motions

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#642] opened 2018-04-02 01:57 UTC
### Steps to reproduce
Load any two models that have related markers, ground reaction forces, or activations as .mot/.sto files to be associated with a motion or states file.

Alone each model plays back the motion and associated motions.

### Expected result
Motions including associated motions are synced.

### Actual result
Only the original motion (state or kinematics) files and any associated motions are ignored (see below). The associated ground reaction forces are ignored and activations associated with the chimp model also disappear.

<img width="1437" alt="screen shot 2018-04-01 at 6 54 25 pm" src="https://user-images.githubusercontent.com/6494122/38180039-3ea1a46e-35de-11e8-91bc-76da53f0b916.png">

### Environment and GUI version
Mac OpenSim 651d29f-2018-03-30

**Comment by jenhicks** [comment] 2018-04-02 17:40
Related to #333 ?

**Comment by aymanhab** [comment] 2018-04-02 20:28
I don't think this is related to #333, we can verify by moving motion slider to one intermediate frame and visualizations should update. I'm not sure if colors of muscles/activations were assumed to behave the same as associated motions because I think they never did in the past as described in #521 
I just created and recorded two models/motions one with experimental markers associated and another with GRF without an issue. There's likely a bug but I need specific steps/files to reproduce/fix.

**Comment by aymanhab** [comment] 2018-04-03 19:10
This is fixed by PR #645 Please verify on next build. Keep in mind that color muscles from file is not an associated motion and will still get lost once the current motion changes.

**Comment by jenhicks** [comment] 2018-04-11 17:32
This is not fixed on my Mac. OpenSim 03d9220-2018-04-09
Maybe this build doesn't have the PR mentioned?

**Comment by jimmyDunne** [comment] 2018-04-11 20:09
I opened two models with a motion and a associated motion each (same motion and external loads for each). When I try to play the motion using the motion player, the animations freezes and will not play. Once I pause the motion player, it takes a few seconds before I can resume interaction with the visualizer window. 

![two_models_no_cup](https://user-images.githubusercontent.com/5296507/38640514-01d9f552-3dc4-11e8-8ff4-4ca8f4174669.png)

**Comment by jenhicks** [comment] 2018-04-11 21:32
@aymanhab I still have the issue that Ajay reports. With marker data, I see the following:

Load 2 versions of gait2354
First model: Load kinematics and then associate marker data -> marker data appears
Second model: Load kinematics -> marker data associated with the first model disappears.

**Comment by aymanhab** [comment] 2018-04-11 21:35
Jen, I think that has always been the behavior. Associated data appear only
when motion is current  (bold) or synced. Can you try in 3.3? Thanks

**Comment by jenhicks** [comment] 2018-04-11 21:42
@jimmyDunne can you test on 3.3? I need to sort out my vm license before I can test on Windows.

**Comment by jenhicks** [comment] 2018-04-11 21:54
@aymanhab If I make the model current, the associated motions are not rendered (maybe expected). But if I delete the motion and associate it again, it still doesn't render

**Comment by jenhicks** [comment] 2018-04-11 22:25
Hmmm ... I see now that you have to not only make the model current but also the motion current. 

Is that consistent with past versions? (i.e., you can have the current motion be one that is not associated with the current model) What does that mean?

**Closed** 2019-02-28 00:05 UTC
Labels: Animation
