### ISSUE TITLE
Analytical shape edits are not propagated to visualizer

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#346] opened 2017-07-28 05:55 UTC
The `Cone`'s *direction* property has no effect on its orientation. Always points upward (along +Y), regardless.

**Comment by aymanhab** [comment] 2018-04-03 22:14
No examples yet, should be easy to fix once we have a model to test with.

**Comment by chrisdembia** [comment] 2018-04-04 17:45
Here you go: [cone.osim.txt](https://github.com/opensim-org/opensim-gui/files/1876920/cone.osim.txt) (remove .txt extension).

The cone height and cone direction are not obeyed. I think this is an opensim-core issue.

**Comment by jimmyDunne** [comment] 2018-04-12 00:06
Changing the cone height or radius had no effect. 

![cone_model.gif](https://images.zenhubusercontent.com/544fc8297c6ccc6277a5b651/b36a5e66-a508-4f83-bc3a-3da0e3f4bcaa)

**Comment by jimmyDunne** [comment] 2018-04-12 16:09
This is issue is to do specifically with the Cone. If there are filed issues (and PR's) elsewhere for the different shapes, it would helpful for you to link them here.

**Comment by aymanhab** [comment] 2018-06-30 21:28
PR #871 hides parameters that are not handled yet (needs fix on API side for orientation, similar to cylinders)

**Comment by chrisdembia** [comment] 2018-07-27 19:09
1. **Brick**: I am able to edit the `half_lengths` of a `Brick` ✔️ , and the visualizer updates appropriately, and the quadrants property does not appear ✔️ .
2. **Ellipsoid**: (a) Editing the `radii` for an`Ellipsoid` has no effect ❌ . (b) The quadrants property is not hidden. ❌ 
3. **Sphere**: Editing `radius` ✔️ ; `quadrants` property is not hidden ❌ .
4. **Cylinder**: Editing `radius` ✔️ and `half_height` ✔️ ; `quadrants` property is not hidden ❌ .
5. **Cone**: Editing `height` ✔️ and `base_radius` ✔️ ; `quadrants` property is hidden ✔️ .

Why was this moved to "Needs Verifying"?

**Comment by aymanhab** [comment] 2018-07-27 19:16
@chrisdembia In the past no changes to Analytical shapes were ever propagated. I agree we should either support or hide quadrants, looking for feedback on that. Elipsoid is implemented as a scaled Sphere, we can hide radii and users modify scale factors. Thoughts?

**Comment by aseth1** [comment] 2018-08-02 21:10
What do `quadrants` mean in the context of `Geometry`? If it is only necessary for wrapping then `WrapGeometry` should define it.

**Comment by chrisdembia** [comment] 2018-08-02 21:18
I don't know why this was moved to "Needs Verifying" if this issue has so far only been addressed for `Cone`.

**Comment by aseth1** [comment] 2018-08-02 21:27
An Ellipsoid is not a scaled Sphere! This is confusing trying to visualize joint surfaces. They are defined by radii for a reason. I don't think we should have scale factors for `Geometry`. If I want a bigger Sphere I should specify a larger radius. If I want a different sized Ellipsoid we should modify its radii, Block its half-lengths, etc... why do we need to confuse it with scale factors?

**Comment by carmichaelong** [comment] 2018-08-14 17:52
@aymanhab 
On W10, 71c8c385. One check does not pass:

1. Brick
a) `half_lengths` changes visualize ✔️  
b) `quadrants` hidden ✔️ 
2. Ellipsoid
a) `radii` changes does not visualize ❌ 
b) `quadrants` hidden ✔️ 
3. Sphere
a) `radius` changes visualize ✔️ 
b) `quadrants` hidden ✔️ 
4. Cylinder
a) `radius` and `half_height` changes visualize ✔️ 
b) `quadrants` hidden ✔️ 
5. Cone
a) `height` and `base_radius` changes visualize ✔️ 
b) `quadrants` hidden ✔️

**Comment by aymanhab** [comment] 2018-08-14 19:13
Thanks @carmichaelong 👍 Can you send me the model with Ellipsoid that you tested with.

**Comment by carmichaelong** [comment] 2018-08-14 20:54
@aymanhab I packed up the 5 models I used to test in the zip attached:

[geometry_models.zip](https://github.com/opensim-org/opensim-gui/files/2288452/geometry_models.zip)

**Comment by aymanhab** [comment] 2018-08-14 22:02
Thanks again @carmichaelong the issue is that the part of the fix on threejs repo side wasn't merged to the opensim-gui repo. Will let you know when I have a build to verify that Ellispoid radii behave as expected.

**Comment by aseth1** [comment] 2018-08-14 23:08
@aymanhab 

> What do quadrants mean in the context of Geometry? If it is only necessary for wrapping then WrapGeometry should define it.

**Comment by aymanhab** [comment] 2018-08-15 01:44
@aseth1 the original plan was to use generic geometry start/end-angles to allow creation of partial surfaces for decorations (half a cylinder, or part of cone etc.)  There was a complication that WrapObjects create separate Geometry components so there was a potential of quadrants/angles getting out of sync. or that both end up shown to users causing confusion. I didn't want users to get stuck with the awkward quadrants forever, so the compromise was to leave quadrants with Geometry for now and not expose them until a clear use-case/separation can be made. Hope this explains.

**Comment by aseth1** [comment] 2018-08-15 17:53
@aymanhab 

1. quadrant is unused by all `Geometry` and has no implementations for drawing partial geometry
2. `WrapObject`s do not derive from `Geometry`
3. derived `WrapObjects` have the specific implementations for handling `quadrants` which for most users (including myself) have a confusing meaning and somewhat arbitrary effect.  I am happy to leave them in legacy code, but shoving them into a new base class we are introducing in 4.0 is not OK.

> I didn't want users to get stuck with the awkward quadrants forever

By baking them into the base Geometry we are enshrining them in the codebase forever.  Since they are unused, it would be appropriate, where design and software maintainability would dictate that they be removed.

**Comment by chrisdembia** [comment] 2018-08-15 17:59
I agree that `quadrants` should not be in `Geometry`. When the feature is added, it will be fine to add the property at that time. It should be a fairly quick fix to remove the property.

**Comment by aseth1** [comment] 2018-08-15 17:59
> the original plan was to use generic geometry start/end-angles to allow creation of partial surfaces for decorations (half a cylinder, or part of cone etc.)

These should simply be different `Geometry` types. It is not the job of a base class to foresee all potential uses and conditions, that is why we can derive,

**Comment by aymanhab** [comment] 2018-08-15 18:31
@aseth1 these are NOT different geometry types, and using inheritance here would be a grave mistake and fundamental misuse of inheritance. A half cylinder is not a kind-of-cylinder (as subtype) it's a cylinder with different attributes!

**Comment by aseth1** [comment] 2018-08-15 20:01
I don't even think it is a kind of `Cylinder`. It is its own `HalfCylinder` or `PartialCylinder` with its own set of attributes. I was disagreeing with:

> use generic geometry start/end-angles

But it seems like you agree that these will be very different attributes for different concrete types so it makes no sense having them in the base. Do we agree that `quadrants` has no current use in `Geometry`? If and when such a think is necessary we can add it to were it belongs, yes?

**Comment by aymanhab** [comment] 2018-08-15 20:04
Yes, @aseth1 I agree to remove quadrants from Geometry 😃

**Comment by aymanhab** [comment] 2018-08-16 21:09
https://github.com/opensim-org/opensim-core/pull/2263 has been opened to remove quadrants. After it's merged, I'll remove the code that hides quadrants and then any further testing can be done on the PR branch if needed.

**Comment by aymanhab** [comment] 2018-08-21 17:06
@carmichaelong Now all the pieces are there, and you have the models, one more round and we're done and can move it to verified. Thanks

**Comment by carmichaelong** [comment] 2018-08-21 18:46
On W10, c73fa614-2018-08-20: all things check out

1. Brick
a) `half_lengths` changes visualize ✔️  
b) `quadrants` hidden ✔️ 
2. Ellipsoid
a) `radii` changes does not visualize ✔️ 
b) `quadrants` hidden ✔️ 
3. Sphere
a) `radius` changes visualize ✔️ 
b) `quadrants` hidden ✔️ 
4. Cylinder
a) `radius` and `half_height` changes visualize ✔️ 
b) `quadrants` hidden ✔️ 
5. Cone
a) `height` and `base_radius` changes visualize ✔️ 
b) `quadrants` hidden ✔️

**Comment by aymanhab** [comment] 2018-08-21 18:53
Thank you @carmichaelong 🥇 for the verification again and thanks @aseth1 and @chrisdembia for the review. 🎆

**Closed** 2018-08-31 22:12 UTC
Labels: Needs Discussion, Visualization, bug
