### ISSUE TITLE
Change default marker size for model and experimental markers to 10mm

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#643] opened 2018-04-02 02:21 UTC
### Steps to reproduce
Preview or associate marker data in the GUI.
Click on the *Markers* under *Motions* in the Navigator.
*marker color* and *marker size* are listed as properties.
Changing the color has an effect on the visualized experimental markers but size has no effect.

### Expected result
*marker size* number reflects the size of the marker

### Actual result
No effect.
<img width="1437" alt="screen shot 2018-04-01 at 7 12 53 pm" src="https://user-images.githubusercontent.com/6494122/38180458-9950c96e-35e1-11e8-8688-e5de26b45a3b.png">

*marker radius* would also be more clear and its units should be *m*.

### Environment and GUI version
Mac OpenSim 651d29f-2018-03-30

**Comment by aymanhab** [comment] 2018-04-02 16:34
This is practically a duplicate of #474 since analytical shapes do not respond to scale changes. Will be addressed together.

**Comment by jenhicks** [comment] 2018-04-02 17:45
Thanks @aseth1 @aymanhab ... keeping issue open so that we can verify this use case is also fixed.

**Comment by aseth1** [comment] 2018-04-02 17:52
Unlike #474, value changes are accepted and *size* does not return to 1.0. Also not obvious that the issues are related.

**Comment by tkuchida** [comment] 2018-04-20 08:02
Current behavior is unexpected and internally inconsistent.

**Steps to reproduce:**
- File > Preview Experimental Data...
- Select test.trc (contained in this ZIP file: [test.zip](https://github.com/opensim-org/opensim-gui/files/1931234/test.zip))
- Can't find markers in Visualizer (Issue #653)
- File > Close All
- File > Preview Experimental Data...
- Select test.trc
- In Navigator, select *Markers* and change `marker size scale`

**Expected behavior:**
Marker size is absolute. Changing from 1.0 to 2.0 makes markers twice as large. Changing again from 2.0 to 2.0 (i.e., editing the field but not changing the numbers) should have no effect. Changing again from 2.0 to 1.999 should make no noticeable difference.

**Actual behavior:**
Marker size is relative *and* you are not permitted to make the same relative change in the marker size twice. Changing from 1.0 to 2.0 makes markers twice as large. Changing again from 2.0 to 2.0 (i.e., editing the field but not changing the numbers) does nothing---which would be expected if the size were absolute. However, now changing from 2.0 to 1.999 makes the markers (just less than) twice as large. Changing 1.999 to 2.0 doubles the size of the markers again.

If the value entered in this box is absolute, then entering 2.0 followed by 1.999 should have no noticeable difference on the size of the markers (they should be 0.05% smaller). If the value entered in this box is relative, then the user should be allowed to enter the same number twice to repeat the relative size change. The current behavior is a hybrid that forbids, for example, doubling in size by entering 2.0 twice in a row, but permits entering 2.0 followed by 1.999.

**Environment:**
AppVeyor artifact OpenSim-dbbbb0c5-2018-04-16.zip

**Comment by jimmyDunne** [comment] 2018-04-29 00:37
I am getting the same behavior as Tom. The Marker size should be absolute or the scale should always be relative to the original size (the difference between 2 and 1.9 would be small, rather than ~doubling it again)

**Comment by jimmyDunne** [comment] 2018-06-01 19:08
> No effect.
Experimental marker color and size (scale factor) can be changed and have an effect 

> marker radius would also be more clear and its units should be m
Markers are not in m, they are scaled by an arbitrary factor.

**Comment by aymanhab** [comment] 2018-06-22 17:19
Having an explicit Experimental Marker Size (m) would be inconsistent with Force Size which is a relative scale up/down. The name of the property is displayed clearly as "Marker Size Scale".  The only thing that's missing is the Preference "Experimental Marker Size" which is being ignored and it has to be either respected or removed. Please advise @jimmyDunne

**Comment by jimmyDunne** [comment] 2018-06-26 16:03
In Preferences, it is 'Experimental Marker Size' which is wrong if you want it to be scale. You will need to change that. 

There is still no way I see of changing the size of the model markers. That needs to be fixed/added as well.

**Comment by aymanhab** [comment] 2018-07-19 01:59
Experimental meker preference is now in mm and is observed. If improvement in Model marker behavior is suggested,  please open a separate issue as they use different mechanisms.

**Comment by aseth1** [comment] 2018-07-24 22:12
The property seems to be a screen size scale factor. At least it is still called `marker size scale`.
This is different from the `experimental marker size` Preference, which is supposed to be the radius in (mm).

Is the preference supposed to be the base size and the property a scale factor applied to that size?

The initial scale factor seems to be strangely assigned. I had the preference set to 1 for two data sets (yellow and blue) and 10 for the third data set (pink). The first two were visible and had a property scale of 1 by default. I made the blue factor 2 and it appeared to double.  Then l I loaded the third set (preference 10mm). Note the `marker size scale` = 0.001!

![image](https://user-images.githubusercontent.com/6494122/43166175-b91fcba6-8f4a-11e8-96d2-9636dd716ff6.png)

Changing the `marker size scale`  of the blue markers then makes them massive. This must now be relative to the new preference value.

![image](https://user-images.githubusercontent.com/6494122/43168520-78d1fac6-8f52-11e8-9ca0-6a90164c9cd4.png)

Interestingly, all the markers view the same size if you scale if you scale them to something that is not 1.0 and then back to 1.0. And this seems to 1.0x the marker size specified in the preference. 

Since there is an editable property to update the marker size live, what is the need for the version in the preference? If the property where just `marker radius` as its absolute size, I think a lot of confusion and unnecessary interactions will go away.

![image](https://user-images.githubusercontent.com/6494122/43168671-ff54deec-8f52-11e8-89fd-e5e64d577782.png)

**Comment by aymanhab** [comment] 2018-07-24 22:32
@aseth1 In my comment above on June 22, I suggested the preference either be removed or used. @jimmyDunne suggested that the default size was too small for his taste, so the preference is used for the default/initial size but you can still scale up/down. I'm not sure it's worth much more trouble but would be good to get feedback from our most extensive user of experimental data @jimmyDunne

**Comment by aymanhab** [comment] 2018-08-07 17:09
@nickbianco or @carmichaelong can you verify

**Comment by nickbianco** [comment] 2018-08-07 18:35
@aymanhab @carmichaelong testing the fix now.

**Comment by nickbianco** [comment] 2018-08-07 22:37
While the specific changes from #945 are working, I did notice a few other things:

- To visualize an experimental marker set that has been loaded, you must double-click the file name in the Navigator (e.g. `subject01_static.trc`). Double-clicking the data object (e.g. `ExperimentalData_0`) will make that object current, but won't visualize it's marker data. This seems inconsistent with how models are visualized after making them current in the Navigator, and could be confusing to users (since you have to expand the Experimental Data tab and then double-click the file name).
- The Experimental Marker Size preference only gets updated in GUI after loading a new marker set to preview. It also doesn't get automatically applied to marker sets already loaded in the GUI. To view markers at the new Experimental Marker Size, the user must:
    1) double-click the previous marker set they would like to view
    2) change the "marker size scale" to something other than what is currently specified
    3) set the "marker size scale" to 1.0

**Comment by nickbianco** [comment] 2018-08-09 21:08
After discussion in the last two daily scrums, the general consensus is to prioritize the following changes:

1. Increasing the default marker size from 5 mm to something more visible (something between 10-15 mm would be fine in my opinion). This would be a quick fix and could prevent users from wanting to change the marker size in the first place.

2. Remove the `marker size scale` option and replace it with an absolute marker size option (in millimeters). The default for a previewed marker set could be the Experimental Marker Size preference. 

Details about implementation and whether or not to incorporate model marker sizing with these changes warrants further discussion with @aymanhab and the rest of the team.

**Comment by aymanhab** [comment] 2018-08-10 18:05
Thanks for the feedback and testing @nickbianco :+1: Please open an issue regarding changing model marker size and default experimental marker size as they need to be the same (not sure if 10 was consensus/eyeball size in 3.3), and another one regarding the removal/modification to scale experimental marker behavior and we'll discuss/prioritize. Thank you.

**Comment by aymanhab** [comment] 2018-08-10 18:07
And since this issue has been actually verified, let's move the issue to proper board.

**Comment by aymanhab** [comment] 2018-08-14 16:38
@chrisdembia The opensim-core change is in, the opensim-gui change is on branch but the builds on opensim-core master are failing for unrelated reasons. How would we get a build of this PR branch with the latest opensim-core master to test/verify?

**Comment by chrisdembia** [comment] 2018-08-14 19:27
@aymanhab the travis-ci build is passing. For appveyor, we need to temporarily alter the C3D performance test.

**Comment by aseth1** [comment] 2018-08-14 23:59
> @aymanhab the travis-ci build is passing. For appveyor, we need to temporarily alter the C3D performance test.

See https://github.com/opensim-org/opensim-core/pull/2258

**Comment by aymanhab** [comment] 2018-08-17 15:56
Ready for test/verification of PR build artifact

**Comment by chrisdembia** [comment] 2018-08-21 18:47
Should this be in Needs Verifying?

**Comment by scrum2a** [comment] 2018-08-22 17:06
See #945.

**Comment by nickbianco** [comment] 2018-08-27 21:52
Retested the changes made in #945, which has already been merged to master. Moving to Verified on Windows.

**Comment by chrisdembia** [comment] 2018-08-28 22:50
On Mac The default Experimental Marker Radius preference is 5.0 for me on a fresh install of 4.0-2018-08-27-088a48d.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/846001/44755139-b1a7f600-aad9-11e8-913f-5a7223565b5d.png">

Everything else works as expected.

**Comment by chrisdembia** [comment] 2018-08-30 17:41
Verified on Mac.

**Comment by jimmyDunne** [comment] 2018-08-30 20:49
Marker default is 10 on 4.0-2018-08-30-a33ffc9. Looks much better!!

**Closed** 2018-08-31 22:11 UTC
Labels: Visualization
