### ISSUE TITLE
Failed to load adolc and ipopt when starting OpenSim in Ubuntu after building from source.

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [opensim-org/opensim-gui#1393] opened 2022-10-13 22:12 UTC
### Steps to reproduce

Follow [Build Instructions](https://github.com/opensim-org/opensim-gui/wiki/Build-Instructions) for Ubuntu, or install from an artifact generated by CI.

### Expected result

After the application has been installed in Ubuntu, you should be able to start OpenSim without any error.

### Actual result

Two errors can appear:

- `Failed to load one or more dynamic libraries for OpenSim. java.lang.UnsatisfiedLinkError: /opt/opensim-gui/sdk/lib/libosimJavaJNI.so: libadolc.so.2: cannot open shared object file: No such file or directory`
- `Failed to load one or more dynamic libraries for OpenSim. java.lang.UnsatisfiedLinkError: /opt/opensim-gui/sdk/lib/libosimJavaJNI.so: libipopt.so.1: cannot open shared object file: No such file or directory`

### Workaround 
Add the following lines at the top of the file `/opt/opensim-gui/bin/opensim`:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/<user_name>/opensim-workspace/opensim-core-dependencies-install/adol-c/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/<user_name>/opensim-workspace/opensim-core-dependencies-install/ipopt/lib
```

### Notes

This is a known issue reported [here](https://github.com/opensim-org/opensim-gui/issues/1255#issuecomment-766095550) (where there is also a workaround) and there is a pull request in the opensim-core repository working on solving it: [#2930](https://github.com/opensim-org/opensim-core/pull/2930)

### Environment and GUI version
Environment: Ubuntu >=18.04
GUI Version: v4.4

**Comment by aymanhab** [comment] 2023-01-24 22:50
Testing the artifacts on a linux machine, the issue is fixed with libgcc but the regular libosim* are not found. Will need to fix before trying to merge. Good progress @AlbertoCasasOrtiz I'll see if I can pick it up from here.

**Comment by AlbertoCasasOrtiz** [comment] 2023-02-09 00:00
@aymanhab I think I have fixed the problem with the libosim* libraries. I also detected that the libcasadi* libraries were not able to find libcasadi.so. Can you test this?

**Comment by luisgizirian** [comment] 2023-02-15 19:40
This is still going on. The workaround mentioned above works beautifully.

**Comment by aymanhab** [comment] 2023-02-16 23:30
@luisgizirian You may want to test the latest main branch to see if the issue has been resolved. Thank you

**Comment by luisgizirian** [comment] 2023-02-17 00:35
Begun running the deployment script on a fresh Ubuntu 22.10 rollout as I type @aymanhab . It should pick the latest main branch by default if I understand correctly. I'll communicate the results back.

**Comment by luisgizirian** [comment] 2023-02-17 02:07
Worked without the need for the workaround @aymanhab! :)

Looks like this issue can be closed?

**Small nit:** even though we're on version 4.5, the loading splash screen still reads as Version 4.4.

**Comment by aymanhab** [comment] 2023-02-17 17:28
Thanks for the update @luisgizirian much appreciated 👍  Yes will close this issue as completed. We typically change the splash-screen only once before an official release, though I agree there's inconsistency now between the screen and internals but we avoid end users downloading a development build and confusing it with an official release.

**Closed by aymanhab** 2023-02-17 17:28 UTC
Labels: Build

**Comment by luisgizirian** [comment] 2023-02-17 18:32
Not to intrude into your processes, maybe a pre-release tag would help clarify and better communicate in order to avoid user-confusion @aymanhab. Just thinking out loud.
