### ISSUE TITLE
For OutputReporter, attempting to edit output_paths causes crash.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#462] opened 2018-01-07 18:46 UTC
OpenSim-4.0.Beta_121517_Mac

# Steps to reproduce

1. Open arm26.osim
2. Raise shoulder coordinate.
3. Tools > Forward Dynamics... > Analyses. Add OutputReporter.
4. Edit the OutputReporter.
5. Click `output_paths` field.
6. GUI crashes.

I've attached a crash log.

[OpenSim4.0MacOutputReporterCrash.txt](https://github.com/opensim-org/opensim-gui/files/1610084/OpenSim4.0MacOutputReporterCrash.txt)

**Comment by aymanhab** [comment] 2018-01-08 22:39
Cant reproduce crash on Windows though I don't get results either.  Things I tried as output specs:
/r_elbow_flex/value
/arm26/r_elbow_flex/value

**Comment by aymanhab** [comment] 2018-01-11 19:58
@aseth1 will take a look.

**Comment by aseth1** [comment] 2018-01-25 19:47
Likely and illegal name exception

**Comment by chrisdembia** [comment] 2018-01-25 23:33
It seems that editing the `output_paths` field is not necessary to cause the crash. I got the crash simply after clicking "Edit" on an OutputReporter, after adding it. I only got that crash once; I could not reproduce it. I can also get the crash by clicking other fields in the Edit dialog box (other than output_paths):

<img width="538" alt="screen shot 2018-01-25 at 3 32 50 pm" src="https://user-images.githubusercontent.com/846001/35418053-03e5c850-01e5-11e8-8759-d09473d44cd8.png">

Sometimes, the crash takes a long time to happen.

**Comment by chrisdembia** [comment] 2018-01-25 23:33
I could not get a crash when adding and editing other analyses.

**Comment by aseth1** [comment] 2018-02-12 22:49
I am assigned to this, but the crash is occurring when selecting the `OutputReporter` analysis to edit as @chrisdembia reported. When i provide an `OutputReporter` in the AnalyzeTool setup file [subject01_Setup_Analyze.xml](https://github.com/opensim-org/opensim-gui/files/1717984/subject01_Setup_Analyze.txt), it appears and clicking edit does not crash it (immediately at least).

<img width="711" alt="screen shot 2018-02-12 at 2 41 46 pm" src="https://user-images.githubusercontent.com/6494122/36123961-4a8adc06-1003-11e8-9444-92b494d18b08.png">

Attempting to populate the list (+) eventually crashes it.

**Comment by aseth1** [comment] 2018-02-15 02:14
Loading `Tug_of_War_Setup_Analyze.xml` in the GUI (build: OpenSim-dd7dc47b-2018-02-11 for Windows) runs and produces results that are the same (but not identical) to `testAnalyzeTool` (locally but different build of core).

However clicking on the Analyses tab yield the red warning icon with this message:

```java.lang.NullPointerException
	at org.opensim.tracking.AbstractToolModel.getAnalysisSet(AbstractToolModel.java:96)
	at org.opensim.tracking.AnalysisSetTableModel.getRowCount(AnalysisSetPanel.java:74)
	at javax.swing.JTable.getRowCount(JTable.java:2662)
	at javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1692)
	at javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1733)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1511)
	at java.awt.Container.doLayout(Container.java:1500)
	at java.awt.Container.validateTree(Container.java:1696)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validateTree(Container.java:1705)
	at java.awt.Container.validate(Container.java:1631)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.ensureCurrentLayout(BasicTabbedPaneUI.java:1447)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPaneUI.java:1467)
	at com.sun.java.swing.plaf.windows.WindowsTabbedPaneUI.setRolloverTab(WindowsTabbedPaneUI.java:104)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.layoutContainer(BasicTabbedPaneUI.java:2400)
	at java.awt.Container.layout(Container.java:1511)
	at java.awt.Container.doLayout(Container.java:1500)
	at java.awt.Container.validateTree(Container.java:1696)
	at java.awt.Container.validate(Container.java:1631)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.ensureCurrentLayout(BasicTabbedPaneUI.java:1447)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPaneUI.java:1467)
	at com.sun.java.swing.plaf.windows.WindowsTabbedPaneUI.setRolloverTab(WindowsTabbedPaneUI.java:107)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.setRolloverTab(BasicTabbedPaneUI.java:575)
	at javax.swing.plaf.basic.BasicTabbedPaneUI.access$2100(BasicTabbedPaneUI.java:54)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mouseMoved(BasicTabbedPaneUI.java:3664)
	at java.awt.Component.processMouseMotionEvent(Component.java:6578)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4539)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by aseth1** [comment] 2018-02-15 02:18
Closing and reopening the AnalyzeTool gets the warning to stop appearing. I can then access the Analyses tab and attempt to edit the OutputReporter, up on which the GUI crashes.

**Comment by aymanhab** [comment] 2018-02-22 19:33
@aseth1 can you clarify if you load a setup file with populated OutputReporter, whether that works and produces expected output or not? Just to make sure that if the editing issue is fixed then we're not stuck with another issue downstream. Thanks

**Comment by aseth1** [comment] 2018-02-22 20:57
@aymanhab Yes, loading and running `Tug_of_War_Setup_Analyze.xml` in the GUI produces the expected results (not identical but very close) compared to the standard in core.

**Comment by aymanhab** [comment] 2018-02-23 17:02
Fix on branch PR #530 pending successful build

**Comment by aseth1** [comment] 2018-02-25 23:31
@aymanhab this bug is "fixed" because it no longer crashes the GUI, but editing is still confusing. One must click `+` then double-click **output_paths** to see the added text field. I suspect most users will click on the down arrow (triangle) icon to expand the list. Can you make it that if you hit `(+)` you automatically jump to the newly added text field? For the longest while i thought nothing was happening then noticed there were in fact spaces in the list. When I finally double-clicked on **output_paths** there were several blank entries in the expanded list.

**Comment by aseth1** [comment] 2018-02-25 23:38
OK it still crashes the GUI, just a bit more delayed. After editing as describe above, I hit `Cancel` and it crashed. Here is the log [crash_report_18-02-25_1535.txt](https://github.com/opensim-org/opensim-gui/files/1756846/crash_report_18-02-25_1535.txt).

**Comment by chrisdembia** [comment] 2018-02-26 02:25
>  For the longest while i thought nothing was happening then noticed there were in fact spaces in the list. When I finally double-clicked on output_paths there were several blank entries in the expanded list.

I had the same experience with the Kinematics analysis.

**Comment by aymanhab** [comment] 2018-02-26 18:38
Crash cancelling out analysis edit should be made into own issue and not be confused with any other random and likely unrelated crashes.

**Comment by chrisdembia** [comment] 2018-02-26 19:29
What if it's the same issue 😮

**Comment by aseth1** [comment] 2018-03-12 22:30
Confirmed that this appears to be working on recent [Windows build](https://www.dropbox.com/home/DevBuilds/frameEditBuild)

**Closed** 2018-06-01 18:36 UTC
Labels: macOS
