### ISSUE TITLE
Enable users to configure lighting in the GUI

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-gui#683] opened 2018-04-25 16:48 UTC
There is no UI control of lighting in the OpenSim visualizer (have to edit the underlying javascript) and using expert mode in the web browser is extraordinarily difficult and inconsistent with the visualizer (#681). Furthermore, there are multiple scene light sources and their names are not indicative of what they do. The purpose of each light source must be made clear and there should be ways to modify lighting directly from the GUI/visualizer.

### Suggestions (in order of complexity)
1. add option for users to turn on/off each light source including model and ambient lighting
2. enable setting the intensity of each light source
3. enable movement of each light source not just the "scene light" in the visualizer 
4. enable changing the direction (orientation) of directional light sources
5. store these settings so the scene can be preserved.

**Comment by aseth1** [comment] 2018-04-25 19:39
related to #314, #477, #519  #613, #668. We are lacking a design/structure for handling user needs for modifying the scene to deliver on our promise to provide beautiful visuals and publication quality images. Documenting the requirements and presenting a design to address  those requirements should be step 0 in addressing these issues.

**Comment by jenhicks** [comment] 2019-02-28 00:04
Closing this issue since it is a duplicate of #688

**Closed by jenhicks** 2019-02-28 00:04 UTC
Labels: Interface, Visualization, enhancement
