### ISSUE TITLE
Foward Tool cannot be run with PointKinematics analysis

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#264] opened 2017-07-08 22:33 UTC
**Steps to reproduce**
- open Models\Pendulum\double_pendulum.osim
- select *Forward Dynamics…* from the *Tools* menu
- in the *Analyses* tab, add a *PointKinematics* analysis
- click *Run*

**Expected behavior**
Simulation runs.

**Actual behavior**
The following dialog box appears:

![fwd](https://user-images.githubusercontent.com/4203505/27989648-1780bbe0-63f2-11e7-86ae-d87938e86051.png)

but no details are provided in the Messages window:
<pre>
Updating Model file from 30000 to latest format...
Loaded model double_pendulum from file C:\Users\tkuchida\GitHub - GUI 4.0 alpha03\opensim\Models\Pendulum\double_pendulum.osim
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
ModelVisualizer ignoring 'Unassigned'; only .vtp .stl and .obj files currently supported.
Running tool double_pendulum.
No external loads will be applied (external loads file not specified).
</pre>

The GUI occasionally crashes (closes) after this (see [hs_err_pid10160.log](https://drive.google.com/a/stanford.edu/file/d/0B1BKpngQdIZITkNNQzBkSjhvZXc/view?usp=sharing)).

**Comment by aymanhab** [comment] 2018-03-26 22:54
This looks like a duplicate of the Analysis edit crash fixed in PR #614 Needs verification

**Comment by jenhicks** [comment] 2018-03-26 23:11
I tested with Arm26 ... no errors on my Mac

**Comment by jimmyDunne** [comment] 2018-04-28 21:29
Tested with Arm26... no errors on W10.

System:W10
Build:04-27-2018

**Closed** 2018-06-01 18:36 UTC
Labels: March2018 Workshop
