### ISSUE TITLE
Saving high-resolution screenshots from the visualizer cuts off the image

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#299] opened 2017-07-16 05:29 UTC
Jen: Key feature of OpenSim 4.0 is being able to create great visuals. Controlling the resolution of the image is a key part of this.

Here's how we could temporarily increase the size of the renderer while taking a screenshot: https://stackoverflow.com/questions/27534206/three-js-screenshot-custom-size-using-an-offscreen-rendere

It would be great to save screenshots as 300 dpi or maybe even 600 dpi.

**Comment by aymanhab** [comment] 2017-12-12 22:49
I implemented the solution suggested and it creates much nicer pngs indeed but you have to specify dimensions (in pixels) 
![opensim_snapshot_1830x1186](https://user-images.githubusercontent.com/3972208/33912602-6d6b4712-df4b-11e7-9e4a-e618688c85ea.png)
![opensim_snapshot](https://user-images.githubusercontent.com/3972208/33912605-73cb075a-df4b-11e7-9b5e-cffb4c0508ff.png)

Still deciding on entry point to avoid clutter. Not exactly DPI spec. but DPI has many players involved and no cross-platform measure it seems.

**Comment by chrisdembia** [comment] 2017-12-12 22:52
Do you mean the end-user must specify the dimensions? Why is that?

**Comment by aymanhab** [comment] 2017-12-14 21:43
The mapping between resolution DPI (misleading)/PPI and inches doesn't seem to be available in a reasonable (non-hacky way). The two options I'd suggest would be either ask user for size in inches and PPI and compute resolution from that (to pass to the code) or just have the user do the multiplication and specify resolution. 
https://www.iprintfromhome.com/mso/understandingdpi.pdf
Either way the function I implemented based on your link above seem to print at arbitrary resolution. Please let me know what you think.

**Comment by chrisdembia** [comment] 2017-12-14 21:53
Ah thanks for explaining; I think I understand. Having the user specify the dimensions in inches and then a separate resolution (in pixels/inch) sounds reasonable, though using inches might be confusing for those outside the US. Having the user specify the dimensions in pixels also sounds fine to me.

My main concern is about preserving the aspect ratio. We should make it hard for the user to change the aspect ratio.

**Comment by aymanhab** [comment] 2018-01-25 18:05
As of now I added a shortcut that when you press 'd' for high-Dpi in 3D window you get upsampled screen capture by a factor of 4. Would be good to know if this works cross platform and on a regular resolution monitors and if the result meets common journal standards  which usually require min DPI but no max/file-size.

**Comment by aseth1** [comment] 2018-01-25 20:33
Consider adding a user preference to set the the resolution factor.

**Comment by tkuchida** [comment] 2018-01-31 07:11
Nice feature! Almost works (using OpenSim-078b8daf-2018-01-26.zip from AppVeyor/artifacts). Two issues:

1. WYSINWYG (the background changed color):

*Visualizer window*
![](https://user-images.githubusercontent.com/4203505/35609109-e33b5d9c-0610-11e8-8c53-8b4ba1264136.png)

*Snapshot*
![](https://user-images.githubusercontent.com/4203505/35609113-e78abcda-0610-11e8-872f-58c5075d51c5.png)

2. If something is being multiplied by 4, I would have expected it to be my native screen resolution rather than the size of the GUI's visualizer window. I got a snapshot of 4860×2452 pixels, which is okay but my guess is that the user would not expect the snapshot size to depend on the size of the GUI panel.

**Comment by aymanhab** [comment] 2018-01-31 17:54
Thanks much for testing/reporting @tkuchida :+1:
1. Indeed, I reproduced that background color issue so will leave the issue open until background color is fixed.
2. As indicated earlier on this issue, the problem with using the screen resolution rather than the graphics window size is that the aspect ratio could be different and the image will be distorted, same for regular snapshot which uses whatever the window size. The goal, in my mind, is to produce 300 DPI images on a typical/low-end machines with minimal effort. If that can be verified it would be great.

**Comment by chrisdembia** [comment] 2018-01-31 18:09
I expected the aspect ratio to be that of the GUI's visualizer window, not of the screen resolution, which allows the user to choose the aspect ratio of the image.

**Comment by tkuchida** [comment] 2018-01-31 20:22
> As indicated earlier on this issue, the problem with using the screen resolution rather than the graphics window size is that the aspect ratio could be different and the image will be distorted, same for regular snapshot which uses whatever the window size.

I'm not advocating that you map the Visualizer window image onto an image with a different aspect ratio: that would distort the image. What I'm saying is that I don't think a user would want a snapshot of 4860×2452 pixels in any situation. I think it would be more common to want an image with a 4:3 or 16:9 aspect ratio. The snapshot should not be a function of the arbitrary size of the Visualizer window because the user would then need to either crop the image manually or carefully adjust the Visualizer window with their mouse to get the desired ratio (likely only approximately)—which they would then be unable to reproduce after closing the window.

Ideally, the user would be able to select the aspect ratio (e.g., 4:3 or native screen resolution) and the viewport is increased either horizontally or vertically to produce the desired aspect ratio. For example, if the Visualizer window is squarish, the snapshot would include the 3D world to the left and right of what can be seen in the Visualizer window. Among the options could be to retain the current aspect ratio of the Visualizer window.

> The goal, in my mind, is to produce 300 DPI images on a typical/low-end machines with minimal effort. If that can be verified it would be great.

Ok, I understand. I agree: the current implementation is minimal effort.

> I expected the aspect ratio to be that of the GUI's visualizer window, not of the screen resolution, which allows the user to choose the aspect ratio of the image.

The user can't really choose the aspect ratio; I didn't really want 1.982055:1.

**Comment by jenhicks** [comment] 2018-03-08 22:15
@aymanhab How do you exercise this feature? It sounds like you are also working on the background color so this should move to in progress.

**Comment by tkuchida** [comment] 2018-03-08 22:27
Press 'd' when the Visualizer Window has the focus. BTW, it might be worthwhile to replace
```js
// original
var screenShotHiRes = renderer.domElement.toDataURL();
// proposed
var screenShotHiRes = renderer.domElement.toDataURL( 'image/jpeg', 0.92 );
```
in OpenSimViewport.js to help ensure a screenshot is always produced. By default, `toDataURL()` generates a PNG, but no file is saved (and no warning/error message is reported) if the number of characters in the file exceeds 65,535---which I believe depends on the frequency content of the image. `0.92` is the default JPEG quality, and should be indistinguishable from the PNG.

**Comment by aymanhab** [comment] 2018-03-08 22:37
Thanks for the note and for the suggestion @tkuchida 

In earlier discussion @chrisdembia indicated preference of non lossy png over jpg, would love to hear from him.
One other potentially useful feature is to replace the button to screencapture with a flyover toolbar with different buttons for png, jpg. Do you think this is 4.0 worthy? @jenhicks

**Comment by jenhicks** [comment] 2018-03-08 22:38
I can't get this feature to work. Maybe because I am using a virtual machine?

**Comment by tkuchida** [comment] 2018-03-09 01:16
> One other potentially useful feature is to replace the button to screencapture with a flyover toolbar with different buttons for png, jpg.

It would be great to get PNG to work reliably. If the user clicks the button to export a screencap and the file size exceeds 65,535 characters, it would be nice to display a message letting them know that the screencap couldn't be generated and how they can fix/work around the problem.

**Comment by jenhicks** [comment] 2018-03-09 16:50
> If the user clicks the button to export a screencap and the file size exceeds 65,535 characters, it would be nice to display a message letting them know that the screencap couldn't be generated and how they can fix/work around the problem.

I think this may have been the issue for me. If I use my laptop screen vs. big screen at work I can save an image.

**Comment by jenhicks** [comment] 2018-03-09 17:06
Having high resolution images in 4.0 definitely seems like a good idea to me. The factor 4 multiplication seems a little arbitrary to me. Some alternate options:

1) Save the image at the highest resolution possible when you click on the camera icon. This seems like potentially the simplest option.
2) Give people options to adjust the resolution and potentially file type.

As a user (2) would be nice, but I'd be fine with (1), too since I could down-sample or convert to a different file type in post processing.

**Comment by aymanhab** [comment] 2018-03-09 17:47
@jenhicks Option 1 would not be hard to implement if we can get the size before we actually create the image, if not we should give an error if size is too big. The number 4 was picked as a start but changing it or setting it as a preference in the Advanced  dropdown would be very easy. On my generic desktop/laptop screen size it produces images with better than 300 dpi which was described as the main goal above
>The goal, in my mind, is to produce 300 DPI images on a typical/low-end machines with minimal effort.

**Comment by tkuchida** [comment] 2018-03-11 06:06
[This page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs#Common_problems) mentions a size limit (under "Common problems"):

![](https://user-images.githubusercontent.com/4203505/37250344-30e934c6-24af-11e8-9dbb-8d5818a5cea3.png)

**Comment by aymanhab** [comment] 2018-03-11 20:03
Thanks @tkuchida The spec of the method used to get the image from canvas states default DPI of 92, which suggests that indeed a factor of 4 is smallest integer to get to 300 DPI. I'm leaning to make this the default and address the size/error issues and leave it at that unless we're aware of use cases where 300 DPI is not enough.

**Comment by aymanhab** [comment] 2018-03-12 22:06
Here's the latest fixes/proposal:
1. ScreenCapture  button always does at least 300 DPI.
2. Pressing  'd' produces close  to 900 DPI capture
3. I changed the plumbing so that there's no size limitation due to URLs size limit above, as such there's no max resolution.
I can expose the scale up factor or file type in advanced settings either on the visualizer side or as an application side setting but it may not be necessary considering that the limitation has been removed.  Let me know what you think. @jenhicks @tkuchida @chrisdembia and @aseth1

**Comment by chrisdembia** [comment] 2018-03-12 22:11
IMO the interface of pressing 'd' is not very clear. What about having a preference that is the scale-up factor, and by default its value is whatever you're using to achieve "at least 300 DPI" (4x?)

**Comment by jenhicks** [comment] 2018-03-12 22:16
I agree that pressing d is not very clear to the user. @chrisdembia 's proposal sounds reasonable to me.

**Comment by aymanhab** [comment] 2018-03-12 22:17
Agreed @chrisdembia The tradeoff is that more options crowd the interface but this sounds reasonable.

**Comment by jenhicks** [comment] 2018-03-14 18:57
@aymanhab Did you add the option to set the preference for resolution? Pressing "d" did not work for me in the 3-13 build. I would either save at a higher resolution when you press the camera button or add a preference in Edit->Preferences or elsewhere. Pressing of "d" is not intuitive and doesn't seem to fit with the rest of our interface.

**Comment by aymanhab** [comment] 2018-03-14 18:59
@jenhicks This is entirely client/visualizer side. The controls menu has a a slider for Scaleup Factor that goes from 1 to 10, defaults to 4.

**Comment by jenhicks** [comment] 2018-03-14 19:23
Ah ... I see the option now.

Behavior on my machine:
- If I set the res to 5 or higher, it turns the entire visualizer black. A black image is saved. I have to restart to be able to see a model again
- At the default 4 setting, the image saved looks good, but the visualizer background turns black (from the default gray) until I click on the visualizer again.

**Comment by aymanhab** [comment] 2018-03-14 20:16
Jen, I fixed the background color issue after the merge. On my desktop I can go up to 10 without issue. What you describe is a browser crash. If 4 is good enough I can make it the max. Would love to hear from others as well.

**Comment by aymanhab** [comment] 2018-03-15 15:24
Can you give us your feedback on Windows, Mac (latest build, Capture Scaleup under Controls) Slider 1-10. Specifically:
- Does it crash or produce black image for settings above 4?
- Would limiting the max to 4 (300 DPI) be sufficient.
 @tkuchida @aseth1 @chrisdembia @jimmyDunne @carmichaelong

**Comment by jenhicks** [comment] 2018-03-15 15:38
@aymanhab Does everyone have access to the dropbox folder with the latest build (3-13)?

**Comment by aymanhab** [comment] 2018-03-15 15:43
No but they can use SourceForge or appveyor.

**Comment by aymanhab** [comment] 2018-03-15 15:52
Would be also good to report what platform was used: Windows, Mac. Windows
on vm

On Mar 15, 2018 8:43 AM, "Ayman Habib" <ahabibsu@gmail.com> wrote:

No but they can use SourceForge or appveyor.

**Comment by jimmyDunne** [comment] 2018-03-15 19:25
(W10 VM on Mac, OpenSim-6d5a4cb4-2018-03-13.zip)

>Does it crash or produce black image for settings above 4?

The saved image seems correct for values EXCEPT for max value (10), which produces a black image. 

When image is saved, the visualizer backgrounds goes black until selected.

**Comment by tkuchida** [comment] 2018-03-18 07:21
Three unexpected behaviors on Windows (AppVeyor artifact OpenSim-0d41eef3-2018-03-14.zip):

1. The snapshot does not capture what is displayed in the Visualizer Window at high `Capture Scaleup` values:

**Visualizer Window**
![](https://user-images.githubusercontent.com/4203505/37563603-ea039c02-2a41-11e8-8aae-140650f79d55.png)

**Snapshot, `Capture Scaleup = 4`**
![](https://user-images.githubusercontent.com/4203505/37563606-ed16158c-2a41-11e8-99a6-23d9bae19308.png)

**Snapshot, `Capture Scaleup = 8`**
![](https://user-images.githubusercontent.com/4203505/37563611-f2f8aa96-2a41-11e8-862b-2a78b5252dfd.png)

**Snapshot, `Capture Scaleup = 10`**
![](https://user-images.githubusercontent.com/4203505/37563613-f67a481e-2a41-11e8-8d99-40f0794a3feb.png)

2. The background turns black, as reported previously.
3. Pressing "d" no longer works. I read all the comments above but didn't see a definitive decision; I assume removing "d" was intentional.

Two additional comments:
- I don't think users will know what "Capture Scaleup" means. Note that the hover text for the camera button is "Snapshot".
- It would be nice to get high-resolution graphics, so limiting to 4x is not ideal.

**Comment by aymanhab** [comment] 2018-03-18 09:39
@tkuchida The d shortcut was removed and replaced with the slider, sorry it wasn't clear in the discussion above. The capture part is puzzling because the scaling is happening indeed as you can see the logo bigger, and I don't know what's different on your machine than others, can you try slider at 1?

Good point regarding slider name, should we change the hover text to Capture, or change slider name? Any preference as a user?

**Comment by tkuchida** [comment] 2018-03-18 09:54
> can you try slider at 1?

Slider at 4 is fine (compare first two images above). I wouldn't expect a problem at 1, but here it is anyway in case you're looking for something I'm missing:

**Visualizer Window**
![](https://user-images.githubusercontent.com/4203505/37564634-26a47b8a-2a57-11e8-9bd5-c01e00c18b72.png)

**Snapshot with `Capture Scaleup = 1`**
![](https://user-images.githubusercontent.com/4203505/37564636-29a5f19c-2a57-11e8-9862-690f160715c5.png)

> should we change the hover text to Capture, or change slider name? Any preference as a user?

There are many possible designs for the interface and text. I think replacing "Capture Scaleup" with "Snapshot Resolution" would be an improvement and would require almost no effort.

**Comment by jenhicks** [comment] 2018-03-19 13:12
I like "snapshot resolution"

**Comment by jenhicks** [comment] 2018-03-19 22:02
@aymanhab In the 3-19 build, the resolution slider is just labeled "Snapshot". Was there not room to fit resolution?

**Comment by aymanhab** [comment] 2018-03-19 22:04
The word is actually there but cutoff, if you drag the dropdown you'll see it. I was leaning to Quality or Size since resolution is already well defined and is different from what the slider is.

**Comment by aymanhab** [comment] 2018-03-20 14:04
Can we agree on a shorter meaningful name so i can change the slider name and move on from this one, thanks.

**Comment by jenhicks** [comment] 2018-03-20 15:36
Snapshot Quality works

**Comment by jenhicks** [comment] 2018-03-20 15:47
@aymanhab While you are updating, could we use consistent capitalization and spacing in the visualizer controls menu? Suggestions are below with an asterisk next to the menu items that I'm proposing to tweak.

Floor
Texture*
Height*
Background Color*
Scene Light
Show FPS
Snapshot Quality*

**Comment by aymanhab** [comment] 2018-03-20 19:21
Thanks @jenhicks All done, should show in the next build. Do you find the Show FPS useful?

**Comment by aymanhab** [comment] 2018-03-21 17:38
Changes made, and built into latest AppVeyor artifact

**Comment by aseth1** [comment] 2018-04-25 16:57
I was not able to save images of the chimp, human and exo models in one scene at even a Snapshot Quality of 1 on my Mac.  I can get snapshots with simpler scenes. I don't think this capability has been completely verified on Mac.

Also editing the Snapshot Quality value is extremely awkward. For example, using the arrow after clicking in the text-box and getting a cursor translates the 3D view.

**Comment by tkuchida** [comment] 2018-04-25 21:37
> using the arrow after clicking in the text-box and getting a cursor translates the 3D view

Similar to #625

**Comment by aseth1** [comment] 2018-06-25 06:20
Screen capture functionality still does not work reliably for me on Mac OpenSim 1e476f2-2018-06-13.

Screen grab:
<img width="946" alt="screen shot 2018-06-24 at 11 16 58 pm" src="https://user-images.githubusercontent.com/6494122/41833338-ca352dbc-7804-11e8-91a2-8b89f7dd5bdc.png">

Snap shot feature at lowest quality is still 5.4MB and yields:
![scapula_clavicle_frames_back](https://user-images.githubusercontent.com/6494122/41833264-6dc188fa-7804-11e8-8c32-dc25e3b1fa3e.png)

This has been particularly frustrating for trying to generate figures for publications and presentations.

**Comment by aymanhab** [comment] 2018-07-19 22:15
Will investigate a bit more, though differences between machines makes testing hard. A reasonable tradeoff that @tkuchida has used in the past was to use jpg with quality parameter.

**Comment by aymanhab** [comment] 2018-07-31 16:36
All interested parties, do you get black image at any time now or just incomplete capture, please let me know as  I never get a black image on any of my machines at the moment. Thank you.

**Comment by jenhicks** [comment] 2018-07-31 16:55
I can't create a black image, but I do get an incomplete image if I maximize the OpenSim window size and set the snapshot quality to 4.

**Comment by nickbianco** [comment] 2018-08-06 20:59
I took a few screenshots, with and without the Visualizer Window maximized, and I got the expected image out.

![opensim_snapshot.png](https://images.zenhubusercontent.com/5b5fce5a634ac264954e72c0/15bc2619-8b02-42b1-8d15-8b3f621bab5d)

I can't find the snapshot quality setting under View Controls on my current build on Windows (OpenSim efbc92ac-2018-08-06). 

Also, when saving an image with the same name as an image file that exists in the save directory, I don't get a prompt to ask if I want to overwrite the current file. That is probably for a separate issue though.

**Comment by aymanhab** [comment] 2018-08-06 21:17
@nickbianco Thanks for testing, I've seen this in an earlier build where first time you launch the gui, some preferences are uninitialized leading to missing snapshot slider. Do you see the slider next time you launch the GUI? If so please open an issue and will address. Thank you

**Comment by nickbianco** [comment] 2018-08-06 21:39
@aymanhab the slider appeared after closing and reloading the GUI. The associated issue (#946) has been created. 

Regarding the snapshots, I get normal behavior except for the case the Jen reported -- Visualizer Window maximized, Snapshot Quality at 4.

**Snapshot Quality 3**
![snap3](https://user-images.githubusercontent.com/23224439/43742296-4615dec0-9986-11e8-9b06-4c4f2ea0233a.png)

**Snapshot Quality 4, image taken at same model position/view angle**
![snap4](https://user-images.githubusercontent.com/23224439/43742303-4f3ae8f6-9986-11e8-942d-65cb8de178e7.png)

**Comment by aymanhab** [comment] 2018-08-06 21:40
Perfect, thank you @nickbianco

**Closed** 2019-02-28 21:54 UTC
Labels: March2018 Workshop, Visualization, help wanted
