### ISSUE TITLE
Loading malformed XML file should be caught and clearly reported in context of model loading rather than waiting until an exception is bubbled up to the JVM

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#351] opened 2017-08-02 23:42 UTC
Reported in #335

**Comment by aymanhab** [comment] 2018-03-27 19:03
Duplicate of #618 in the sense that a SimTK Exception is thrown and caught by GUI. Nothing more to be done on GUI side. If API catches the exceptions and throw OpenSim Exceptions that would be more graceful but again not GUI issue. Recommend verifying and closing

**Closed** 2022-11-28 18:27 UTC
