### ISSUE TITLE
How to display Connectors (Sockets) in the Properties panel

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#101] opened 2017-03-06 07:13 UTC
This is not a bug.

The Properties panel has a section for Connectors, with a neat dropdown to change the connectee. I like this. I think the dropdown should show paths to disambiguate, if there are multiple components with the same name. Also, this dropdown is redundant with the “connector_parent_frame_connectee_name” property…not sure what to do about this…perhaps the GUI should hide “connector_…_connectee_name” properties. Also, I think Connectors should be its own tab, like Properties and Outputs.

**Comment by aseth1** [comment] 2018-03-12 19:00
Duplicate of #344. Closing.

**Closed by aseth1** 2018-03-12 19:00 UTC
Labels: enhancement
