### ISSUE TITLE
Typo in OSIM file does not produce a dialog box

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#618] opened 2018-03-23 05:32 UTC
### Steps to reproduce
Attempt to open a model file containing a typo (e.g., this one: [arm26-typo.txt](https://github.com/opensim-org/opensim-gui/files/1840271/arm26-typo.txt); see "r_shoulder_elev_this_is_a_typo").

### Expected result
GUI catches exception, notifies user, and returns to the idle state it was in before the user attempted to open the model.

### Actual result
Rectangle keeps bouncing back and forth in status bar, suggesting that the GUI never stops trying to open the model:
![](https://user-images.githubusercontent.com/4203505/37812978-57c8840a-2e20-11e8-819b-3ce2643b8f5d.png)
The rectangle kept bouncing even after successfully opening a valid model file.

### Environment and GUI version
AppVeyor artifact OpenSim-587ee9d9-2018-03-21.zip

**Comment by aymanhab** [comment] 2018-03-23 15:03
![capturetypo](https://user-images.githubusercontent.com/3972208/37836714-687f94f0-2e70-11e8-90b0-d5c36f01fa14.JPG) Causes less than graceful handling downstream

**Comment by aymanhab** [comment] 2018-03-26 19:35
Fixed in latest build, please verify when you have a chance @tkuchida Thank you

**Comment by jenhicks** [comment] 2018-03-26 23:15
On my mac I do not see the persistent rectangle. I get the following error:

java.lang.RuntimeException: SimTK Exception thrown at Joint.cpp:138:
  Internal bug detected: Joint::constructCoordinate() MotionTypes do not correspond to coordinates
  (Assertion 'static_cast<unsigned>(numCoordinates()) == _motionTypes.size()' failed).
  Please file an Issue at https://github.com/simbody/simbody/issues.
  Include the above information and anything else needed to reproduce the problem.
	at org.opensim.modeling.opensimSimulationJNI.new_Model__SWIG_1(Native Method)
	at org.opensim.modeling.Model.<init>(Model.java:784)
	at org.opensim.view.FileOpenOsimModelAction.loadModel(FileOpenOsimModelAction.java:123)
	at org.opensim.view.FileOpenOsimModelAction.loadModel(FileOpenOsimModelAction.java:117)
	at org.opensim.view.FileOpenOsimModelAction$1.run(FileOpenOsimModelAction.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tkuchida** [comment] 2018-03-30 08:01
> Fixed in latest build, please verify when you have a chance @tkuchida Thank you

IIRC the GUI used to display a dialog box alerting the user that there was a problem loading the model. I think the dialog box was helpful. Now, there is no dialog box and, furthermore, one part of the GUI reports success and another part of the GUI reports failure.

**Messages window is :smile:…**
<pre>
Updating Model file from 20303 to latest format...
Loaded model arm26 from file C:\Users\tkuchida\Desktop\arm26-typo.osim
</pre>

**…but the model does not appear in the Visualizer Window and there's a :red_circle: error :cry:**
<pre>
java.lang.RuntimeException: SimTK Exception thrown at joint.cpp:138:
  Internal bug detected: Joint::constructCoordinate() MotionTypes do not correspond to coordinates
  (Assertion 'static_cast<unsigned>(numCoordinates()) == _motionTypes.size()' failed).
  Please file an Issue at https://github.com/simbody/simbody/issues.
  Include the above information and anything else needed to reproduce the problem.
	at org.opensim.modeling.opensimSimulationJNI.new_Model__SWIG_1(Native Method)
	at org.opensim.modeling.Model.<init>(Model.java:783)
	at org.opensim.view.FileOpenOsimModelAction.loadModel(FileOpenOsimModelAction.java:123)
	at org.opensim.view.FileOpenOsimModelAction.loadModel(FileOpenOsimModelAction.java:117)
	at org.opensim.view.FileOpenOsimModelAction$1.run(FileOpenOsimModelAction.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>

AppVeyor artifact OpenSim-4077dd7b-2018-03-29.zip

**Comment by aymanhab** [comment] 2022-11-28 17:55
Duplicate of another open issue.

**Closed by aymanhab** 2022-11-28 17:55 UTC
Labels: March2018 Workshop
