### ISSUE TITLE
Rotating experimental data fails

### ISSUE THREAD

**Issue by A-Artemis** [opensim-org/opensim-gui#1493] opened 2024-03-04 20:17 UTC
### Steps to reproduce

1. Open a `.trc` file by clicking File->Preview Experimental Data.
2. Open the experimental data in the navigator to right click the `.trc` and click Transform...
3. Rotate X by 90 degrees (I have tried Y and Z with angle [90, 180, 270, 360].
4. Click on Save As... (I use the default name which is `transformed_XXX.trc`).
5. Click on OK to close the dialogue box.
6. Open the newly created  `transformed_XXX.trc` file by clicking File->Preview Experimental Data.

### Expected result
- The transformed `.trc` is opened and can be seen in the Visualizer Window, and correctly rotated.

### Actual result
- The transformed data is not visible in VIsualizer Window. Below you can see both ExerimentalData_ in the Navigator but only 1 set of makers (this is from the original `.trc`) yet the markers of the new `.trc` are loaded. The floor and background is removed to see more of the environment.
![image](https://github.com/opensim-org/opensim-gui/assets/32452555/349cf8eb-1d04-48eb-b4e8-aa953c32f18d)

- There is a chance that the saved `transformed_XXX.trc` is created but has 0 bytes.
![image](https://github.com/opensim-org/opensim-gui/assets/32452555/5e158519-4462-4daa-a3f8-d6a0d36e26f2)

- According to the documentation [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Previewing+Motion+Capture+%28Mocap%29+Data) it should be possible to view the rotation happen live with the use of the arrow keys, this does not work.

### Environment and GUI version

- OpenSim GUI version 4.5-2024-01-10-3b63585
- Windows 11 x64
- Data as a `.txt` so that it can be uploaded here. [35_34_mokka.txt](https://github.com/opensim-org/opensim-gui/files/14486716/35_34_mokka.txt)

- The data is taken from [CMU Graphics Lab Motion Capture Database](http://mocap.cs.cmu.edu/search.php?subjectnumber=%&motion=% ), subject 35 with motion 34. The `.c3d` data is downloaded and exported to a `.trc` with [Mokka](https://www.c3d.org/c3dapps.html). This `.trc` is what I open in OpenSim.
- I have had a lot of trouble using the CMU dataset with OpenSim (scaling and XYZ-framing issues). If there is a better workflow (in Python preferably) to handle experimental data then please let me know. My goal is to get the angles of each joint coordinate in the OpenSim model in a `.csv`, which can then be used for AI training. My current workflow is `.c3d -> .trc -> Inverse Kinematics -> .mot -> .csv`

**Comment by mrrezaie** [comment] 2024-03-10 08:19
Hi, related to https://github.com/opensim-org/opensim-gui/issues/1385 and https://github.com/opensim-org/opensim-gui/issues/1344

**Comment by aymanhab** [comment] 2024-05-22 21:35
Visualizer rotation should be fixed by #1507 will reassess. I would not use the GUI for such workflow, and go for all python solution utilizing jupyter notebooks and opensim as described here 
https://github.com/opensim-org/opensim-models/tree/master/notebooks
I'd be happy to help you set this up, and would be wonderful if you "donate" the resulting script to the community (logistics TBD)

**Comment by aymanhab** [comment] 2024-05-23 18:02
The issue was rotating data is fixed in these build artifacts @A-Artemis and @mrrezaie 
https://github.com/opensim-org/opensim-gui/actions/runs/9198670131
While I couldn't reproduce the 0 size file, it's possible it's a downstream effect. Please check the artifacts and let me know.

**Comment by mrrezaie** [comment] 2024-05-23 19:13
Hi @aymanhab, I tested the latest artifact and everything worked perfectly. Thanks for the fix.

**Comment by aymanhab** [comment] 2024-05-23 20:25
Awesome, thanks @mrrezaie for the quick turnaround 👍  and thanks @A-Artemis for reporting. Will merge after review

**Closed** 2024-06-11 21:21 UTC
