### ISSUE TITLE
Editing Socket property causes OpenSim to close

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#529] opened 2018-02-22 23:02 UTC
### Steps to reproduce
- open arm26.osim
- in Navigator, expand *Joints* and click *r_shoulder*
- in Properties tab of Properties window, click `../r_humerus` beside "PhysicalFrame:child_frame" label, select "ground" from the drop-down box, and then click somewhere in the Visualizer window

### Expected result
Property value changes.

### Actual result
OpenSim closes.

### Environment and GUI version
AppVeyor artifact OpenSim-2fd23ef3-2018-02-20.zip

**Comment by aymanhab** [comment] 2018-02-25 10:30
![capture01](https://user-images.githubusercontent.com/3972208/36640431-4ee53d3a-19d3-11e8-9f37-281adcbfb39d.JPG)

**Comment by aymanhab** [comment] 2018-03-01 23:51
Tree is invalid, we may be able to make test more upstream to give more informative message.

**Comment by aymanhab** [comment] 2018-04-25 18:38
This is looking like an API issue, I'm beefing up the test case testContext so that it can be reproduced entirely in C++. Sequence is as follows:
- We make a joint edit that causes invalid tree (e.g. creates loop)
- initSystem throws exception
- We report error and try to undo the change
- Some left over "bodies" from the failed initSystem cause the undo to fail leaving model in limbo state, throwing non OpenSim::Exception

**Comment by aseth1** [comment] 2018-04-25 21:43
1. loops should not cause an invalid tree. We detect them and break the loop(s). Connecting a joint to a frame on the same frame of the body is inavlid and should throw.
2. What does "and try to undo the change" mean? In the exception case, the Model will have intermediate bodies and you cannot at that point use that Model to "restore" anything.

In this case, the new ground offset should not have been invalid. Ground always has a valid index, 0. I'll look into it some more.

**Comment by aymanhab** [comment] 2018-04-25 23:12
All API calls are replicated in PR #2159.  I welcome suggestions for how to change the calls to garcefully handle the unsuccessful edit.

**Comment by aymanhab** [comment] 2018-05-26 15:30
Crash has been fixed on API side, multiple error messages, one is blank. The issue can be verified while I look into the source of the blank error dialog.

**Comment by tkuchida** [comment] 2018-05-26 18:43
> Crash has been fixed on API side, multiple error messages, one is blank. The issue can be verified while I look into the source of the blank error dialog.

[Crash fixed; multiple errors, one blank.](http://www.sixwordstories.net/)

**Comment by aseth1** [comment] 2018-05-26 22:59
@aymanhab are you referring to the issues with sockets in #587? Are you saying the API is has multiple error messages and one is blank?

**Comment by aymanhab** [comment] 2018-05-26 23:51
Yes @aseth1 I'm referring to #587, and I'm still trying to find the source for the empty error message.

**Comment by aymanhab** [comment] 2018-05-30 19:12
Since other exceptions were handled properly, this seems like another corner case that needs handling by core. Please let me know otherwise.

**Comment by aymanhab** [comment] 2018-06-22 23:29
Single meaningful error message now and operation is undone as expected.

**Comment by aseth1** [comment] 2018-07-26 23:44
Verified on Windows OpenSim_cea85df3-2018-07-18. Correctly throws if the child and parent frames are the same and when they share the same base frame.

**Closed** 2019-02-28 00:12 UTC
Labels: Editing, bug
