### ISSUE TITLE
After opening a second model, the "model offset" dialog is populated with incorrect values the first time the dialog is opened

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-gui#737] opened 2018-05-12 08:14 UTC
### Steps to reproduce
- open Gait10dof18musc\subject01.osim
- open a second instance of Gait10dof18musc\subject01.osim
- in *Navigator*, right-click the second "walk_subject01" item and select *Display > Model Offset…*
- close and re-open "Model Offset" dialog, again for the second model

### Expected result
"Model Offset" dialog displays the amount by which the model has been offset from the world origin.

### Actual result
**After opening the "Model Offset" dialog box the first time:**
![](https://user-images.githubusercontent.com/4203505/39955292-20e960ac-5581-11e8-9b8e-6546fdc7df1b.png)

**After closing and re-opening the "Model Offset" dialog box a second time (again for the second model):**
![](https://user-images.githubusercontent.com/4203505/39955293-2443c256-5581-11e8-8094-8e4813b697ed.png)

Issues related to model offset: #88, #734

### Environment and GUI version
AppVeyor artifact OpenSim-75fdf108-2018-05-11-win64.exe

**Comment by aymanhab** [comment] 2018-05-22 17:19
Thanks for reporting @tkuchida I believe you're correct that the model offset values are incorrect first time but they should all be good on subsequent times. I have a fix for that in the pipe (basically the issue is that it takes some variable amount of time for the offsets computed in visualizer to be propagated to GUI, worked on my machine during testing but is a bit flaky).

**Comment by jenhicks** [comment] 2018-06-01 21:22
Fixed for me... (Mac 5/31 build)

**Comment by carmichaelong** [comment] 2018-07-23 21:21
Tested on original case, as well as adding another 5 random models.

Fixed on Windows artifact:
OpenSim cea85df3-2018-07-18

**Closed** 2018-07-27 21:38 UTC
Labels: Interface, bug
