### ISSUE TITLE
Wrap geometry quadrant display and muscle path around wrap object display unexpected

### ISSUE THREAD

**Issue by apoorvar** [opensim-org/opensim-gui#691] opened 2018-04-26 22:27 UTC
I loaded the simple, 1-dof model we built as part of the Dynamic Walker dry run (attached). As the knee is flexed, you would expect the muscle to wrap smoothly around the wrap object. Instead, the muscle path is piecewise-linear--  you can see the points where the muscle comes into and out of contact with the wrap surface, but the path between those points is a straight line segment.

I believe this issue was referenced in #352 and based on comments from 4/5/18, may have been fixed? Not sure.

Separately, the wrap object quadrant was specified to be 'x', which for this model and the shown pose, should be upward. The behavior seems consistent with this, but the display of the wrap object seems to be consistent with the 'y' quadrant. I would expect to see a half-cylinder with the curved-half facing upwards (in the screenshot)

![image](https://user-images.githubusercontent.com/7460161/39334651-5883b338-4964-11e8-8cad-0f4835be3a63.png)

[myReflexModel.txt](https://github.com/opensim-org/opensim-gui/files/1953204/myReflexModel.txt)

Tested on Mac OSX 10.11, GUI version downloaded on 3/27 (for the workshop, I believe)

**Comment by apoorvar** [comment] 2018-05-17 15:15
Sorry, I should've specified before-- the wrapping path looks smooth in the API visualizer

![image](https://user-images.githubusercontent.com/7460161/40186586-57e9c948-59aa-11e8-9483-20fb0ec71ea6.png)
![image](https://user-images.githubusercontent.com/7460161/40186606-61e25d5c-59aa-11e8-8080-083873057826.png)

**Comment by tkuchida** [comment] 2018-05-29 03:29
See the "glmax1_r" muscle in [Rajagopal2015.osim](https://github.com/opensim-org/opensim-models/blob/master/Models/RajagopalModel/Rajagopal2015.osim).

### Steps to reproduce:
- open the model
- right-click Bodies -> Display -> Hide
- right-click Forces/Muscles/all/*glmax1_r* -> Display -> Show Only
- right-click Bodies/pelvis/*Gmax1_at_pelvis_r* -> Display -> Show Only
- in Coordinates panel, change hip_flexion_r to 120

| **Results in 3.3** | **Results in OpenSim 75fdf108-2018-05-11** |
| --- | --- |
| ![](https://user-images.githubusercontent.com/4203505/40636772-b680fd00-62b5-11e8-91d8-e16af32e88dc.png) | ![](https://user-images.githubusercontent.com/4203505/40636775-ba103616-62b5-11e8-8ead-deece6ed3dd9.png) |

**Comment by jimmyDunne** [comment] 2018-05-29 20:43
W10, OpenSim-ffdf2f78-2018-05-29-win64.exe

The quadrant from @tkuchida's example seems to be the same as 3.3

![gmax1_wrap_quadrant](https://user-images.githubusercontent.com/5296507/40684266-cb5af650-6345-11e8-86f7-ce3b0923187c.png)

However, the muscle path does not seem to be going over the wrap. Below is a lower angle of above. Is doesn't seem correct?

![gmax1_wrap](https://user-images.githubusercontent.com/5296507/40684371-01607b9e-6346-11e8-83cb-8a8b65db8938.png)

**Comment by aymanhab** [comment] 2018-05-29 22:35
@aseth1 & @tkuchida Please let me know if you can use the branch from PR #802 or if I should merge the PR so you have a build cross-platform to test with.

**Comment by aymanhab** [comment] 2018-05-29 22:38
![opensim_snapshot](https://user-images.githubusercontent.com/3972208/40689275-5fde6284-6356-11e8-88df-3945686ec98b.png)

**Comment by tkuchida** [comment] 2018-05-29 23:21
> Please let me know if you can use the branch from PR #802 or if I should merge the PR so you have a build cross-platform to test with.

Looks good. Is there a big degradation in performance? Unfortunately, I don't have an environment set up for building the GUI. I can grab a build if you upload it, but it's probably easiest to just merge the PR and I can get the artifact.

**Comment by aymanhab** [comment] 2018-05-30 16:25
Thanks for reporting @tkuchida It should be easy to hide those generated pathpoints to reduce artifacts. Is the wrapping display correct otherwise? How about the responsiveness when moving a coordinate slider?
The shadows have not been changed for a while so it is likely unrelated. The washout of the model marker is likely due to color used for emissive value of the material, a separate issue.

**Comment by aymanhab** [comment] 2018-05-30 16:46
![opensim_snapshot_wrappts1](https://user-images.githubusercontent.com/3972208/40734829-5e9b81ca-63ee-11e8-971e-0b4af53219ba.png)

**Comment by aymanhab** [comment] 2018-05-30 23:07
@tkuchida Please let me know if path drawing is now ok for paper figure, will keep this issue open to improve performance based on feedback. Thanks.

**Comment by aymanhab** [comment] 2018-05-30 23:29
Yes please, muscle display should look like the screen capture above.

**Comment by tkuchida** [comment] 2018-05-30 23:51
I'm still seeing a bunch of spheres along muscle paths in AppVeyor artifact OpenSim-43c1be65-2018-05-30-win64.exe:

![](https://user-images.githubusercontent.com/4203505/40753560-9ce56b90-6429-11e8-8b30-f925d829eb82.png)

**Comment by aymanhab** [comment] 2018-05-31 00:45
@tkuchida I'm not sure what build you're using since there were multiple made today but here's what I see on my screen with default everything using build with installer on windows 
OpenSim-e1c6a4db-2018-05-30-win64.exe
![apoorva1](https://user-images.githubusercontent.com/3972208/40754968-0ef69162-6431-11e8-9708-7dbb196d3ab4.png)

**Comment by aymanhab** [comment] 2018-05-31 00:47
![apoorva2](https://user-images.githubusercontent.com/3972208/40755065-83d570d4-6431-11e8-898e-a1d905d103b2.png)

**Comment by tkuchida** [comment] 2018-05-31 01:04
> I'm not sure what build you're using

Oh I didn't realize there were multiple builds today. I asked whether you wanted me to try OpenSim-43c1be65-2018-05-30-win64.exe (which was the most recent AppVeyor artifact at the time) and you said yes. I'll try the new one.

**Comment by aymanhab** [comment] 2018-05-31 01:08
Sorry, my bad for not tracking the commit number. The one I was using is the first artifact to come with installer.

**Comment by tkuchida** [comment] 2018-05-31 19:16
Still doesn't look fixed in AppVeyor artifact OpenSim-e49a8bde-2018-05-31-win64.exe:

![](https://user-images.githubusercontent.com/4203505/40802858-a8f3e086-64cb-11e8-902b-7fca30c9a58e.png)

### Steps to reproduce:
- open Rajagopal2015 model
- glmax1_r -> Display -> Show Only (and wait ~10 seconds while each muscle disappears)

**Comment by aymanhab** [comment] 2018-05-31 19:20
@tkuchida "ShowOnly" has some quirk that needs fixing on the visualizer side, can you just "hide" what you don't want for now

**Comment by aymanhab** [comment] 2018-06-12 18:36
![opensim_snapshot_reflex](https://user-images.githubusercontent.com/3972208/41309921-da8b8dca-6e34-11e8-86d8-52cc43b688b8.png)

**Comment by carmichaelong** [comment] 2018-07-25 21:08
Looks to be ok on W10 Pro, OpenSim cea85df3-2018-07-18. See below for details:

These are with a muscle point preference of 1.05

Simple knee:
![wrap-simple](https://user-images.githubusercontent.com/7455790/43222336-b7e75e06-9004-11e8-90c6-b4f2d6de5607.JPG)

Rajagopal glmax1:
![wrap-glmax1](https://user-images.githubusercontent.com/7455790/43222379-d0d86e64-9004-11e8-9d2c-16fda7685a3f.JPG)

Rajagopal lower limbs:
I've circled a section that looked similar to a section that Tom had circled before. Further inspection on this model showed that these were (real) wrap points in the model.
![wrap-lowerlimbs-edit](https://user-images.githubusercontent.com/7455790/43222497-275b2024-9005-11e8-8b8d-ce9ec9e8d010.jpg)

**Comment by chrisdembia** [comment] 2018-07-26 20:55
I attempted to verify this issue on Mac (OpenSim cea85df-2018-07-18).

The wrapping of the muscle paths looks better (same as what @carmichaelong sees).

Simple knee:
<img width="312" alt="screen shot 2018-07-26 at 1 49 47 pm" src="https://user-images.githubusercontent.com/846001/43287757-c9de64ac-90da-11e8-94d2-66e7f247e0d8.png">

Rajagopal glmax1:
<img width="409" alt="screen shot 2018-07-26 at 1 47 55 pm" src="https://user-images.githubusercontent.com/846001/43287724-b434dab4-90da-11e8-9c3a-c8f674897f07.png">

**Closed** 2018-07-27 21:16 UTC
