### ISSUE TITLE
Joint Reaction Analysis example does not run

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#545] opened 2018-02-26 18:28 UTC
**Case 1:**
### Steps to reproduce
Run it out of box from files here: https://simtk-confluence.stanford.edu/display/OpenSim/__40__Example+-+Estimating+Joint+Reaction+Loads

### Expected result
It works.

### Actual result
Error that "child" is not a frame. From the code, this makes sense from [this line](https://github.com/opensim-org/opensim-core/blob/f8e7b4f047e2e66b23c1895a63995200b8f33b0d/OpenSim/Analyses/JointReaction.cpp#L305)

(include screen grabs where appropriate)
![image](https://user-images.githubusercontent.com/7455790/36687724-4185a6a4-1adf-11e8-8e60-eee920d6cdc5.png)

**Case 2:**
### Steps to reproduce
Trying to fix above case, changed all "express_in_frame" to "ground"

### Expected result
It works.

### Actual result
RTTI error

![image](https://user-images.githubusercontent.com/7455790/36687884-a7c5a4b4-1adf-11e8-9ae7-93844ec98b9b.png)

### Environment and GUI version
Windows 10, 022518-win64

**Comment by aymanhab** [comment] 2018-04-09 16:38
@carmichaelong is this a duplicate of the core issue 2145? Thanks

**Comment by carmichaelong** [comment] 2018-04-09 18:55
It looks like Case 1 would likely be fixed if 2145 is resolved. It's unclear to me whether Case 2 would be fixed.

**Comment by aymanhab** [comment] 2018-04-24 17:41
@jenhicks I think this should move to backlog for now until the opensim-core issue is fixed then we can verify if this gets fixed or not.

**Comment by aymanhab** [comment] 2018-04-25 18:50
Done, thanks @jenhicks

**Comment by aymanhab** [comment] 2018-05-22 20:36
Had this been addressed on the core side @aseth1 @carmichaelong ?

**Comment by aymanhab** [comment] 2018-05-29 02:42
Please try to run this from command line, if successful please note, otherwise it's an opensim-core issue.

**Comment by tkuchida** [comment] 2018-06-06 00:51
Possibly fixed by https://github.com/opensim-org/opensim-core/pull/2200 ("Answers look about right and only slightly different").

**Comment by jenhicks** [comment] 2018-07-23 21:15
Here's the current link to the tutorial:
https://simtk-confluence.stanford.edu/display/OpenSim/Example+-+Estimating+Joint+Reaction+Loads

**Comment by jenhicks** [comment] 2018-07-23 21:22
I tried to run joint reaction analysis but get the following error. I'm not sure if this is pilot error.
java.lang.RuntimeException: std::exception
	at org.opensim.modeling.opensimActuatorsAnalysesToolsJNI.AnalyzeTool_run__SWIG_0(Native Method)
	at org.opensim.modeling.AnalyzeTool.run(AnalyzeTool.java:154)
	at org.opensim.tracking.AnalyzeToolModel$AnalyzeToolWorker.construct(AnalyzeToolModel.java:139)
	at org.opensim.swingui.SwingWorker$2.run(SwingWorker.java:130)
[catch] at java.lang.Thread.run(Thread.java:745)

**Comment by aymanhab** [comment] 2018-07-23 23:01
@jenhicks I ran to completion after changing the kinematics for external load specification and external loads file to refer to my directory layout. Will compare results to 3.3 but not sure if you did these steps as well or tried to run the files out of the box. Also is there a text version of the instructions instead of watching the video? Thanks.

**Comment by jenhicks** [comment] 2018-07-23 23:12
I changed the files to match my directory layout. There is a readme included in the zip of the example, though it may be out of date.

Were you testing on Windows or Mac?

**Comment by aymanhab** [comment] 2018-07-24 15:55
Testing on Windows both SO, JR run out of the box, results are almost identical to those in OutputReference, for case 2 they are identical to 3.3. That said there're improvements that could be made though same exist in 3.3:
- Kinematics for external loads were specified (@aseth1 recommends against it)
- File for kinematics-of-external-loads marked in red in GUI, not clear if found (no errors reported)
- There're files in both OutputReference of download and in ResultsStaticOptimization and they are different (check rec_fem activations for example), the latter should be removed

**Comment by jenhicks** [comment] 2018-07-24 15:57
Thanks for the update @aymanhab Can you file a separate issue for the example issues you note? You could put this in OpenSim core repo

**Comment by jenhicks** [comment] 2018-07-24 16:06
I was able to run on Mac. It was having trouble loading the static optimization forces file. When you file an issue for improving the example, can you also make a note to make the folder names simpler (there are spaces, dashes, periods), which may have contributed.

**Closed** 2018-07-27 21:47 UTC
Labels: Documentation, March2018 Workshop, Tools
