### ISSUE TITLE
Running a GUI script: "Non-ASCII character"

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#557] opened 2018-02-26 21:59 UTC
### Steps to reproduce

1. Run the addMetabolicsProbe or CMC_EvaluateResults GUI script.

### Expected result

The script runs

### Actual result

Error in the scripting shell:

>  File "<string>", line None
SyntaxError: Non-ASCII character in file '/Users/carawelker/Documents/OpenSim/4.0.Beta/sdk/Scripts/addMetabolicProbes.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

I wasn't able to reproduce this on my machine. Maybe Cara inadvertently changed the encoding of these files.

### Environment and GUI version

Mac OpenSim 2416f17-2018-02-25

**Comment by jenhicks** [comment] 2018-04-11 17:34
I can't reproduce this either ... closing.

**Closed by jenhicks** 2018-04-11 17:34 UTC
Labels: Documentation, macOS
