### ISSUE TITLE
Mac app hangs on splash screen

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-gui#709] opened 2018-05-04 20:58 UTC
### Steps to reproduce

Open Mac app

### Expected result

App opens

### Actual result

App hangs. If I Force Quit and open the app again, it usually opens.

### Environment and GUI version

Mac OpenSim cb3043e-2018-04-23

**Comment by aymanhab** [comment] 2018-06-20 20:32
Just installed and didn't have an issue. Caveat is that the install dialog showed behind other windows. Not sure we can control that. I suggest closing unless there's a way to reproduce consistently.

**Comment by chrisdembia** [comment] 2018-06-20 20:35
Was this on a fresh machine? Try reinstalling?

**Comment by aymanhab** [comment] 2018-06-20 21:12
@chrisdembia I have  iMacPro and a laptop and don't see the issue on either. You reported the issue earlier.

**Comment by chrisdembia** [comment] 2018-06-20 21:14
Yes, I have the issue on my MacBook, and I've had the issue for months now.

**Comment by aymanhab** [comment] 2018-07-19 22:17
No way for me to debug this since it happens on install and doesn't reproduce on my osx machines. Would be great to capture the scenario and investigate then. @chrisdembia what osx version you're seeing this on, and are you installing for yourself or all users?

**Comment by chrisdembia** [comment] 2018-07-20 00:48
I am installing for all users, and I'm using macOS High Sierra.

**Comment by chrisdembia** [comment] 2018-07-24 18:41
This is still occurring for me, and @aymanhab witnessed the issue. It seems to be an issue with jxbrowser. The GUI does eventually launch, but without the visualizer. We used Activity Monitor to "Sample Process" and obtained the following sample from the operating system: [Sample_of_OpenSim_Mac_nojxbrowser.txt](https://github.com/opensim-org/opensim-gui/files/2224941/Sample_of_OpenSim_Mac_nojxbrowser.txt)

Clicking "Window > Visualizer" causes the following red-stop-sign exception in the GUI (and the Visualizer still does not show): 
[Sample_of_OpenSim_Mac_nojxbrowser_JavaStopSignBacktrace.txt](https://github.com/opensim-org/opensim-gui/files/2224943/Sample_of_OpenSim_Mac_nojxbrowser_JavaStopSignBacktrace.txt)


I think the issue is the same one that we tried to fix with the following hack in the installer script: 
https://github.com/opensim-org/opensim-gui/blob/cea85df356478f3b89b7dec7b0c34b99156fd35e/Installer/macOS/scripts/postinstall#L26-L39

**Comment by chrisdembia** [comment] 2018-07-24 18:58
The app hangs even if it's not the first time launching the app after installing.

**Comment by aymanhab** [comment] 2018-07-24 19:04
Could it be related to installing for all users that it requires higher permissions? Did you try install for current user?

**Comment by chrisdembia** [comment] 2018-07-24 19:11
> Did you try install for current user only?

I just tried that and I got an error message ("The installation failed."):

<img width="733" alt="screen shot 2018-07-24 at 12 11 11 pm" src="https://user-images.githubusercontent.com/846001/43160666-aa704bcc-8f3a-11e8-8dfe-c4b994d61494.png">

**Comment by chrisdembia** [comment] 2018-08-09 17:43
I am still having this issue. Am I really the only one?

**Comment by jimmyDunne** [comment] 2018-08-09 18:02
> This is still occurring for me, and @aymanhab witnessed the issue. It seems to be an issue with jxbrowser. The GUI does eventually launch, but without the visualizer.

This is what was happening to me in #450. It was a conflict with an existing app (rescueTime). The only way for me to get around it has been to close rescueTime, open OpenSim, reopen rescueTime. If I try to open the application whenever rescueTime is open, I get the behavior you are describing— there must be some other app that this is happening with.

**Comment by chrisdembia** [comment] 2018-08-28 23:07
@jimmyDunne thank you so much for that hint. I think the [Contexts](https://contexts.co) app is the culprit for me.

**Comment by jimmyDunne** [comment] 2018-08-31 20:54
That's frustrating since Contexts looks really useful. Do you have to shut it down every time you want to use the OpenSim GUI?

**Comment by chrisdembia** [comment] 2018-08-31 21:29
That's what I've been doing today. I might reach out to the Contexts developer to see if they have any ideas.

**Comment by aymanhab** [comment] 2018-08-31 21:32
Is it related to JxBrowser or Java or NetBeans? this would be a common known problem I'd think

**Comment by aymanhab** [comment] 2018-08-31 21:33
Or could be related to the number of threads we spawn on Mac (through the other third-party libraries)?

**Comment by chrisdembia** [comment] 2018-08-31 21:45
This is related to the Visualizer window / JxBrowser.

Why would number of threads be an issue?

**Comment by aymanhab** [comment] 2018-08-31 21:54
I'm trying to think of system resources that different processes are competing for, we know JxBrowser spawns many threads, we can try to limit that if this is the issue or just build a stripped down app with only JxBrowser and see if it plays nicer with these applications.

**Comment by chrisdembia** [comment] 2018-09-01 00:44
I emailed the Contexts developer.

**Comment by chrisdembia** [comment] 2018-11-15 23:45
_BlockUntilNextEventMatchingListInModeWithFilter  may be the culprit

https://github.com/kenorb-contrib/SEGV/issues/18

https://github.com/coteditor/CotEditor/issues/558

[Sample of Contexts.txt](https://github.com/opensim-org/opensim-gui/files/2587436/Sample.of.Contexts.txt)
[Sample of OpenSim.txt](https://github.com/opensim-org/opensim-gui/files/2587437/Sample.of.OpenSim.txt)
Log from OpenSim and Contexts:

**Comment by aymanhab** [comment] 2018-11-16 00:14
Some scope would help, what machines and/or applications cause this? Is it osx version specific?

**Comment by chrisdembia** [comment] 2018-11-16 00:17
Only on Mac. Not specific to 10.14 (Had the issue on 10.13 also). The conflict is only with my Contexts app.

**Comment by chrisdembia** [comment] 2018-11-16 06:05
- https://jxbrowser.support.teamdev.com/support/discussions/topics/9000041632
- https://stackoverflow.com/questions/41557279/jxbrowser-java-ipc-external-true-vm-argument
- https://www.teamdev.com/downloads/jxbrowser/javadoc/com/teamdev/jxbrowser/chromium/BrowserCore.htm
- https://stackoverflow.com/questions/39899103/jxbrowser-on-macosx-using-swt-deadlockl

**Closed** 2022-11-22 21:14 UTC
Labels: bug, macOS, Needs Discussion
